# Generated by Django 2.2.27 on 2022-03-08 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_text', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=60)),
                ('anio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('sinopsis', models.CharField(max_length=700)),
                ('votos', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritas', models.ManyToManyField(to='app.Pelicula')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
